!====================================================================
! Generated by Y X liu, 2007/8/26
!
! (C) Copyright Liu Yi-Xin 
!               Peking univ., Beijing, China
!====================================================================
program main_lyx
!__________________________________________________________________
!
!  This is the program engine for domain recognition, domain counting,
!  boundary tracing and feature parameters caculating.
!__________________________________________________________________
!
use dflib
use lyxTK
implicit none
integer imgn1,imgn2
integer ::image_rgb(1:n1,1:n2) ! store read-in rgb image
integer ::image_in(1:n1,1:n2)  ! store the origin image in gray scale mode 
integer ::image_bin(1:n1,1:n2)
integer thresh
integer ::image_label(1:n1,1:n2)
integer numdomain
integer ::image_bound(1:n1,1:n2) 
integer hist(256)
integer mode ! mode=1: if image_in(j,i)>=thresh then image_in(j,i)=255; mode=2: invert
type (domain_features) ::predf,df   ! domain features. pre - previous
type (domain_struct) ::predi,di     ! domain inner region (contain the boundary)
type (domain_struct) ::predb,db     ! domain boundary (stored in tracing order)
integer ::nplist(MAX_DOMAIN_NUM)    ! number of points list of all domains within an image
type (image_domains) ::dlist(1:MAX_IMAGE_NUM) ! store domain info for every images
real ::circum(1:MAX_DOMAIN_NUM)     ! the circumstance list of all domains within an image 
! graphics
integer(2) xwidth, yheight, cols, rows
integer(2) vx,vy ! the viewport upper-left display position 
integer rgb,oldrgb,red,green,blue
integer(2) status,res
type (windowconfig)  myscreen
common myscreen
real*8 xmin,xmax,ymin,ymax ! for setwindow use
TYPE (wxycoord) wxy
character*32 filename
   ! --- graphic text
integer(2) numfonts,ftindex
integer ftheight,ftwidth
type (fontinfo) ftinfo
type (xycoord) xyt
type (domain_point) labelpos(MAX_DOMAIN_NUM)
character*3 gtext
character*256 gtext2
! general
integer i,j,k,mm
!
! testing field
!
xwidth  = myscreen.numxpixels
yheight = myscreen.numypixels
cols    = myscreen.numtextcols
rows    = myscreen.numtextrows
numfonts=initializefonts()
ftindex=setfont("t'Tahoma'h18pb")
ftindex=getfontinfo(ftinfo)
ftheight=ftinfo%pixheight
ftwidth=ftinfo%avgwidth   ! important, ftinfo%pixwidth=0 for Tahoma font, since it is not a fixed width font.
!
imgn1=13
imgn2=35
DEAL_IMAGES: do mm=imgn1,imgn2
! *****load image*********************************************
vx=1
vy=50
write(filename,"(A11,I3.3,A4)") "images/time",mm,".bmp"
!if(mm<10) then
!	write(filename,"(A13,I1,A5)") "images/time (",mm,").bmp"
!else if(mm<100) then
!	write(filename,"(A13,I2,A5)") "images/time (",mm,").bmp"
!else
!	write(filename,"(A13,I3,A5)") "images/time (",mm,").bmp"
!end if
call graphicsmode()
oldrgb=setcolorrgb(#00FFFF) !yellow
status=rectangle($GBORDER,vx-1,vy-1,n2+vx,n1+vy) !draw boundary rect
call loadimage(filename,int(vx),int(vy))
!
! *****read image*********************************************
do i=1,n2
	do j=1,n1
		image_rgb(j,i)=getpixelrgb(j+vx-1,i+vy-1)
		call integertorgb(image_rgb(j,i),red,green,blue)
		if(red==green .and. red==blue) then
			image_in(j,i)=red
		else
			write(*,*) "wrong image format!"
			pause
		end if
	end do
end do
!
! *****test: read image*********************************************
vy=vy+n1+20
oldrgb=setcolorrgb(#00FFFF) !yellow
status=rectangle($GBORDER,vx-1,vy-1,vx+int2(n2),int2(n1)+vy) !draw boundary rect
do i=1,n2
	do j=1,n1
		rgb=rgbtointeger(image_in(j,i),image_in(j,i),image_in(j,i))
		res=setpixelrgb(j+vx-1,i+vy-1,rgb)
	end do
end do
!
! *****threshold of image*********************************************
thresh=176
mode=1 
call threshold(image_in,image_bin,thresh,mode)
vy=vy+n1+20
oldrgb=setcolorrgb(#00FFFF) !yellow
status=rectangle($GBORDER,vx-1,vy-1,n1+vx,n2+vy) !draw boundary rect
do i=1,n2
	do j=1,n1
		rgb=rgbtointeger(image_bin(j,i),image_bin(j,i),image_bin(j,i))
		res=setpixelrgb(j+vx-1,i+vy-1,rgb)
	end do
end do
write(filename,"(A14,I3.3,A4)") "inout/bin-demo",mm,".bmp"
res=saveimage(filename,int(vx),int(vy),int(vx+n2-1),int(vy+n1-1))
!
! *****labeling*********************************************
! the label is from 1 to a MAX_DOMAIN_NUM if there is. It means that
! we can only identify MAX_DOMAIN_NUM domains. 
call labeling(image_bin,image_label,numdomain,nplist)
!vx=vx+n2+20
!vy=1
!oldrgb=setcolorrgb(#00FFFF) !yellow
!status=rectangle($GBORDER,vx-1,vy-1,n1+vx,n2+vy) !draw boundary rect
!do i=1,n2
!	do j=1,n1
!		rgb=rgbtointeger(image_label(j,i)*255,0,image_label(j,i)*255)
!		res=setpixelrgb(j+vx-1,i+vy-1,rgb)
!	end do
!end do
!res=saveimage('inout/label-demo.bmp',int(vx),int(vy),int(vx+n2-1),int(vy+n1-1))
!
! ***** Add domain inner points to dlist ****************************
dlist(mm-imgn1+1)%nd=numdomain
allocate(dlist(mm-imgn1+1)%labels(numdomain))
if(mm==1) dlist(mm-imgn1+1)%maxlabel=0 ! set the initial maxlabel to 0 since no new domain has been added yet.
allocate(dlist(mm-imgn1+1)%inners(numdomain))
allocate(dlist(mm-imgn1+1)%boundaries(numdomain))
allocate(dlist(mm-imgn1+1)%features(numdomain))
call getdomain_inners(image_in,image_label,dlist(mm-imgn1+1),nplist)
vx=vx+n2+20
vy=50
oldrgb=setcolorrgb(#00FFFF) !yellow
status=rectangle($GBORDER,vx-1,vy-1,n1+vx,n2+vy) !draw boundary rect
do i=1,n2
	do j=1,n1
		rgb=rgbtointeger(0,0,0)
		res=setpixelrgb(j+vx-1,i+vy-1,rgb)
	end do
end do
do k=1,dlist(mm-imgn1+1)%nd
	do i=1,dlist(mm-imgn1+1)%inners(k)%np
		rgb=rgbtointeger(dlist(mm-imgn1+1)%inners(k)%p(i)%pv,dlist(mm-imgn1+1)%inners(k)%p(i)%pv,dlist(mm-imgn1+1)%inners(k)%p(i)%pv) !(k*255/dlist(mm-imgn1+1)%nd,0,k*255/dlist(mm-imgn1+1)%nd)
		res=setpixelrgb(dlist(mm-imgn1+1)%inners(k)%p(i)%y+vx-1,dlist(mm-imgn1+1)%inners(k)%p(i)%x+vy-1,rgb)
	end do
end do
write(filename,"(A16,I3.3,A4)") "inout/label-demo",mm,".bmp"
res=saveimage(filename,int(vx),int(vy),int(vx+n2-1),int(vy+n1-1))
! ***** END Add domain inner points to dlist END *********************
!
! *****domain boundary detection**************************** 
image_bound=image_label
do i=1,dlist(mm-imgn1+1)%nd
	call traceboundary(image_bound,i,circum(i),nplist(i))
end do
!vy=vy+n1+20
!oldrgb=setcolorrgb(#00FFFF) !yellow
!status=rectangle($GBORDER,vx-1,vy-1,n1+vx,n2+vy) !draw boundary rect
!do i=1,n2
!	do j=1,n1
!		if(image_bound(j,i)==255) then
!			rgb=rgbtointeger(255,255,255) ! white, so the boundary is indicated as white lines
!		else
!			rgb=rgbtointeger(0,0,0) 
!		end if
!		res=setpixelrgb(j+vx-1,i+vy-1,rgb)
!	end do
!end do
!res=saveimage('inout/boundary-demo.bmp',int(vx),int(vy),int(vx+n2-1),int(vy+n1-1))
!
! ***** get domain boudaries ****************************************
call getdomain_boundaries(image_bound,dlist(mm-imgn1+1),nplist)
vy=vy+n1+20
oldrgb=setcolorrgb(#00FFFF) !yellow
status=rectangle($GBORDER,vx-1,vy-1,n1+vx,n2+vy) !draw boundary rect
do i=1,n2
	do j=1,n1
		rgb=rgbtointeger(0,0,0) 
		res=setpixelrgb(j+vx-1,i+vy-1,rgb)
	end do
end do
do k=1,dlist(mm-imgn1+1)%nd
	do i=1,dlist(mm-imgn1+1)%boundaries(k)%np
		rgb=rgbtointeger(255,255,255) !(k*255/dlist(mm-imgn1+1)%nd,k*255/dlist(mm-imgn1+1)%nd,k*255/dlist(mm-imgn1+1)%nd)
		res=setpixelrgb(dlist(mm-imgn1+1)%boundaries(k)%p(i)%y+vx-1,dlist(mm-imgn1+1)%boundaries(k)%p(i)%x+vy-1,rgb)
	end do
end do
write(filename,"(A19,I3.3,A4)") "inout/boundary-demo",mm,".bmp"
res=saveimage(filename,int(vx),int(vy),int(vx+n2-1),int(vy+n1-1))
! ***** END get domain boundries END ********************************
!
! ***** get domain features ****************************************
call getdomain_features(dlist(mm-imgn1+1),circum)
!
! ***** END get domain features END ****************************************
!
! ***** domain identification ****************************************
if(mm>imgn1) then
	call identifydomain(dlist(mm-imgn1),dlist(mm-imgn1+1))
else
	allocate(dlist(mm-imgn1+1)%labels(dlist(mm-imgn1+1)%nd)) 
	do k=1,dlist(mm-imgn1+1)%nd
		dlist(mm-imgn1+1)%labels(k)=k
	end do
	dlist(mm-imgn1+1)%maxlabel=dlist(mm-imgn1+1)%nd
end if
! ***** END domain identification END ****************************************
!
! ***** draw domain label ****************************************
! --- draw domain
vy=vy+n1+20
oldrgb=setcolorrgb(#00FFFF) !yellow
status=rectangle($GBORDER,vx-1,vy-1,n1+vx,n2+vy) !draw boundary rect
do i=1,n2
	do j=1,n1
		rgb=rgbtointeger(0,0,0)
		res=setpixelrgb(j+vx-1,i+vy-1,rgb)
	end do
end do
do k=1,dlist(mm-imgn1+1)%nd
	do i=1,dlist(mm-imgn1+1)%inners(k)%np
		rgb=rgbtointeger(dlist(mm-imgn1+1)%inners(k)%p(i)%pv,dlist(mm-imgn1+1)%inners(k)%p(i)%pv,dlist(mm-imgn1+1)%inners(k)%p(i)%pv) !(k*255/dlist(mm-imgn1+1)%nd,0,k*255/dlist(mm-imgn1+1)%nd)
		res=setpixelrgb(dlist(mm-imgn1+1)%inners(k)%p(i)%y+vx-1,dlist(mm-imgn1+1)%inners(k)%p(i)%x+vy-1,rgb)
	end do
end do
! --- draw label
oldrgb=setcolorrgb(#00FF00) ! green
call getlabel_pos(dlist(mm-imgn1+1),labelpos,ftheight,ftwidth)
do i=1,dlist(mm-imgn1+1)%nd
	call moveto(labelpos(i)%y+vx-1,labelpos(i)%x+vy-1,xyt)
	write(gtext,"(I3.2)") dlist(mm-imgn1+1)%labels(i)
	call outgtext(gtext)
end do
! --- save image
write(filename,"(A20,I3.3,A4)") "inout/drawlabel-demo",mm,".bmp"
res=saveimage(filename,int(vx),int(vy),int(vx+n2-1),int(vy+n1-1))
! ***** END draw domain label END ********************************
!
! ***** histogram of image ********************************************* 
!call histgram(image_in,hist)
!open(UNIT=7,FILE='inout/hist.txt')
!do i=1,256
!	write(7,*) i-1,hist(i)
!end do
!close(7)
!vx=vx+n2+20
!vy=1
!call setviewport(vx-1,vy-1,vx+n2,vy+n1)
!xmin=0.0
!xmax=256.0
!ymin=0.0
!ymax=maxval(hist(2:256))
!call setwindow(.TRUE.,xmin,ymin,xmax,ymax)
! draw frame
!oldrgb=setcolorrgb(#00FFFF) !yellow
!status=rectangle_w($GBORDER,xmin,ymin,xmax,ymax)
! draw curve
!oldrgb=setcolorrgb(#00FF00) ! full green
!call moveto_w(1.0_8,dble(hist(1)),wxy)
!do i=2,256
!	status=lineto_w(dble(i),dble(hist(i)))
!end do
! ***** END histogram of image END *************************************** 
!
! ***** Data output ******************************************************
vx=vx+n2+50
vy=50
oldrgb=setcolorrgb(#00FF00)
call moveto(vx,vy,xyt)
write(gtext2,*) "Data Analysis Results"
call outgtext(gtext2)
vy=vy+ftheight
call outgtext('')
vy=vy+ftheight
call moveto(vx,vy,xyt)
write(gtext2,*) "Image      C                A             V           R             H           gcx           gcy"
call outgtext(gtext2)
do i=1,dlist(mm-imgn1+1)%nd
	vy=vy+ftheight+ftheight/2
	call moveto(vx,vy,xyt)
	write(gtext2,"(I8.2,F10.2,I,I,F10.2,I,I,I)") dlist(mm-imgn1+1)%labels(i),            &
					   dlist(mm-imgn1+1)%features(i)%C, dlist(mm-imgn1+1)%features(i)%A, &
	                   dlist(mm-imgn1+1)%features(i)%V, dlist(mm-imgn1+1)%features(i)%R, &
					   dlist(mm-imgn1+1)%features(i)%H,                                  &
					   dlist(mm-imgn1+1)%features(i)%gcx, dlist(mm-imgn1+1)%features(i)%gcy
	call outgtext(gtext2)
end do
! ***** END data output END **********************************************
!
end do DEAL_IMAGES
! ***** Data analysis and output ****************************************
! --- output domain number counting
open(UNIT=7,FILE='data/domainnumber.txt')
do i=1,imgn2-imgn1+1
	write(7,*) imgn1+i-1,dlist(i)%nd 
end do
close(7)
! --- output domain features
do i=1,dlist(imgn2-imgn1+1)%maxlabel
	write(filename,"(A13,I3.2,A4)") "data/features",i,".txt"
	open(UNIT=7,FILE=filename)
	do j=1,imgn2-imgn1+1
		do k=1,dlist(j)%nd
			if(dlist(j)%labels(k)==i) then
				write(7,"(I,F10.2,I,I,F10.2,I,I,I)") imgn1+j-1, dlist(j)%features(k)%C, dlist(j)%features(k)%A, &
	                   dlist(j)%features(k)%V, dlist(j)%features(k)%R, dlist(j)%features(k)%H, &
					   dlist(j)%features(k)%gcx, dlist(j)%features(k)%gcy
			end if
		end do
	end do
	close(7)
end do
! ***** END data output END ********************************
read(*,*)
end program