!====================================================================
! Generated by Liu Yi-Xin, 2007/9/7
!
! (C) Copyright Liu Yi-Xin 
!               Peking univ., Beijing, China
!====================================================================
module lyxTK
!__________________________________________________________________
!
!  This module are designed to define constants, user data type and 
!  procedures for thickening_TDGL project. 
!__________________________________________________________________
!
! ***** Constants *******************************************************
!
integer, parameter ::n1=60 ! y direction, the first subscript of image array due to column major (column <=> y)
integer, parameter ::n2=60 ! n1*n12 is the image size
integer, parameter ::MAX_IMAGE_NUM=200 ! the max image numbers to be analysed
integer, parameter ::MAX_DOMAIN_NUM=255 ! the max domain numbers in the image. ATTENTION: MAX_DOMAIN_NUM<=255.
integer, parameter ::MIN_DOMAIN_POINTS=5 ! the min points which a domain must contain. Otherwise, it is not a domain but noise.
!logical, parameter ::IS_CONTAIN_BOUNDARY_DOMAIN=.FALSE. ! ,TRUE. for contain the domain whose boundary is on the image boundary.
integer, parameter ::DOMAIN_LABEL_SPACE=3 ! the space between domain and label text in pixel
!
! ***** END Constants END ***************************************************
!
!
! ***** User data types *******************************************************
!
type DOMAIN_POINT
	integer x ! x coordinates
	integer y ! y coordinates
	integer pv ! the gray value of the corresponding points
end type DOMAIN_POINT
type DOMAIN_STRUCT
	integer np ! number of points
	type (DOMAIN_POINT), pointer ::p(:) 
end type DOMAIN_STRUCT
type DOMAIN_FEATURES
	real C           ! circumstance
	integer A           ! area
	integer V           ! volume
	real R           ! radius
	integer H           ! maximun height
	integer gcx,gcy  ! (gcx,gcy) is the gravity center  
end type DOMAIN_FEATURES
type IMAGE_DOMAINS
	integer nd       ! number of domians in the image
	integer, pointer ::labels(:) ! since in each image, the same domain may change their intrinsic labels. 
	                             ! So this label maintain the domain itself to indentify each other clearly.
								 ! labels(i) <=> inners(i) <=> boundaries(i) <=> features(i)
	integer maxlabel ! the max label of the domain list of a series of images prior to this image
					 ! To ensure each domain has an unique label of the image list.				  
	type (DOMAIN_STRUCT), pointer ::inners(:)      ! the subscript is the label, so as follows
	type (DOMAIN_STRUCT), pointer ::boundaries(:)
	type (DOMAIN_FEATURES), pointer ::features(:)
end type IMAGE_DOMAINS
!
! ***** END User data types END ********************************************
!
!
! ***** Interfaces ***************************************************
!
!
!
! ***** END Interfaces END *******************************************
!
end module lyxTK